version: "3.8"
services:
  db:
    image: mysql:5.7
    environment: MYSQL_ROOT_PASSWORD: password
    volumes: ["./db/init.sql:/docker-entrypoint-initdb.d/init.sql"]
    ports: ["3306:3306"]

  backend:
    build: ./backend
    ports: ["8000:8000"]
    depends_on: [db]

  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    depends_on: [backend]
